spring:
  application:
    name: weatherapp

openweather:
  api:
    key: 622153acdf6aa18abd2537dd009d0a4c
    url: https://api.openweathermap.org/data/2.5/weather
    location: https://api.openweathermap.org/geo/1.0/direct